services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d user_db" ]
      interval: 20s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: UserService
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_HOST=postgres
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - FILE_STORAGE_LOCATION=/app/storage
      - MAX_FILE_SIZE=3MB
      - MAX_REQUEST_SIZE=15MB
    volumes:
      - file_storage:/app/storage
    restart: unless-stopped

volumes:
  postgres_data:
  file_storage:
