services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - 'RABBITMQ_DEFAULT_USER=admin'
      - 'RABBITMQ_DEFAULT_PASS=admin'
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d customer_db && pg_isready -U admin -d account_db"]
      interval: 20s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_HOST=postgres
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    restart: unless-stopped

  account-service:
    build:
      context: ./account-service
    container_name: account-service
    ports:
      - '8081:8080'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_HOST=postgres
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - CUSTOMER_SERVICE_URL=http://customer-service:8080
      - CUSTOMER_SERVICE_USERNAME=admin
      - CUSTOMER_SERVICE_PASSWORD=admin
    restart: unless-stopped

volumes:
  postgres_data:
